# Generated by Django 5.0.6 on 2024-06-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_62_app', '0003_alter_userprofile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
    ]
