# Generated by Django 5.0.6 on 2024-06-28 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_62_app', '0011_contact_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='project_showcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(blank=True, max_length=200)),
                ('technologies_used', models.CharField(blank=True, max_length=1000)),
                ('project_description', models.TextField(blank=True, max_length=2000)),
                ('project_link', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='project_showcase_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_images', models.ImageField(upload_to='project_images/')),
                ('project_showcases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='task_62_app.project_showcase')),
            ],
        ),
    ]
