# Generated by Django 5.0.6 on 2024-06-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_62_app', '0012_project_showcase_project_showcase_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_showcase',
            name='project_link',
            field=models.URLField(blank=True),
        ),
    ]
