# Generated by Django 5.0.6 on 2024-06-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_62_app', '0016_alter_project_showcase_project_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_showcase',
            name='project_images',
            field=models.ImageField(blank=True, null=True, upload_to='images1/'),
        ),
    ]
